# =========================================
# SERVER
# =========================================
server:
  port: ${PORT:8080}  # Render setzt PORT automatisch

# =========================================
# SPRING APPLICATION
# =========================================
spring:
  application:
    name: erp-system-backend

  # ===============================
  # DATASOURCE (PostgreSQL)
  # ===============================
  datasource:
    url: ${DATABASE_URL}  # JDBC URL
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    hibernate:
      ddl-auto: create  # create, update, validate, none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # ===============================
  # JACKSON
  # ===============================
  jackson:
    serialization:
      indent_output: true

  # ===============================
  # SPRING SECURITY USER (optional, nur für lokale Tests)
  # ===============================
  security:
    user:
      name: ${SPRING_USER:erp}           # Default Benutzer lokal
      password: ${SPRING_PASSWORD:erp}   # Default Passwort lokal

# =========================================
# JWT CONFIG
# =========================================
jwt:
  secret: ${JWT_SECRET:meinSehrSicheresGeheimnis123456789}  # Default lokal
  expiration: 86400000  # Millisekunden (1 Tag)
  issuer: erp-backend

# =========================================
# LOGGING
# =========================================
logging:
  level:
    root: INFO
    com.erp.backend: DEBUG
  file:
    name: logs/erp-backend.log

# =========================================
# MANAGEMENT / ACTUATOR
# =========================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,env,httptrace
  endpoint:
    health:
      show-details: always
